url: https://developair.ir
title: Developair
email: h4lmed@gmail.com

authors:
  Hamed Moghadasi:
    name: Hamed Moghadasi
    display_name: Hamed Moghadasi
    gravatar: c66919cb194f96c696c1da0c47354a6a
    email: h4lmed@gmail.com
    page: authors/hamed
    linkedin : https://linkedin.coms/in/hamedmoghadasi
    github: https://github.com/HamedMoghadasi
    stackoverflow: https://stackoverflow.com/users/6797509/hamed-moghadasi
  Shahrzad Jahanbaz:
    name: Shahrzad Jahanbaz
    display_name: Shahrzad Jahanbaz
    gravatar: 12e480a364a5c19214f99b4dfe9a11d5
    email: shahrzadJahanbaz@gmail.com
    page: authors/shahrzad
    linkedin : https://linkedin.coms/in/shahrzad-jahanbaz-2b7915141
    github: https://github.com/shahrzadJahanbaz
    stackoverflow: https://stackoverflow.com/users/6797509/hamed-moghadasi

description: > 
  As developers, we share our knowledges at developair.ir.

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"
  skin: classic
  social_links:
    twitter: developair-ir
    github: developair-ir
    linkedin: developair-ir

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

header_pages:
  - about.md

google_analytics: G-BEDD986SZM

defaults:
  - scope:
      path: ""
    values:
      image:
        path: /assets/img/public.png